[project]
name = "undermine-goblin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Darnikus", email = "fake@email.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
undermine-goblin = "undermine_goblin:main"

[build-system]
requires = ["uv_build>=0.12.20,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.16.9",
]

[tool.ruff.lint]
select = ["E", "F", "W", "I", "B", "UP"]
ignore = []