# Generated by Django 6.1.1 on 2026-10-05 20:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0002_pricehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricehistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
